FROM mysql:8.0.29

RUN apt update \
    && apt install -y \
    && locales \
    && sed -i -e 's/# \(ja_JP.UTF-8\)/\1/' /etc/locale.gen \
    && locale-gen \
    && update-locale LANG=ja_JP.UTF-8

ENV LANG=ja_JP.utf8 \
    LC_ALL=ja_JP.utf8 \
    TZ=Asia/Tokyo