# Dockerfileのベストプラクティス→ http://docs.docker.jp/develop/develop-images/Dockerfile-best-practices.html
# Pythonのtarファイル→ https://www.python.org/downloads/source/

FROM ubuntu:20.04

EXPOSE 8000

# "RUN export"で環境変数を設定することはできない
ENV PATH=/home/lib/poetry/bin:$PATH \
    POETRY_HOME=/home/lib/poetry

# "apt-get list --installed | <パッケージ名>" でパッケージのバージョンを確認し、
# "<パッケージ名>=<バージョン>"でバージョン指定  Ex.) tzdata=2022a-0ubuntu0.20.04
RUN apt-get update && apt-get install -y \
    tzdata=2022a-0ubuntu0.20.04

# アルファベット順に並べること
RUN apt-get update && apt-get install -y \
    build-essential=12.8ubuntu1.1 \
    curl=7.68.0-1ubuntu2.11 \
    git=1:2.25.1-1ubuntu3.4 \
    language-pack-ja=1:20.04+20220211 \
    libbz2-dev=1.0.8-2 \
    libdb-dev=1:5.3.21~exp1ubuntu2 \
    libffi-dev=3.3-4 \
    libgdbm-dev=1.18.1-5 \
    liblzma-dev=5.2.4-1ubuntu1.1 \
    libmysqlclient-dev=8.0.29-0ubuntu0.20.04.3 \
    libncursesw5-dev=6.2-0ubuntu2 \
    libreadline-dev=8.0-4 \
    libsqlite3-dev=3.31.1-4ubuntu0.3 \
    libssl-dev=1.1.1f-1ubuntu2.13 \
    mysql-client=8.0.29-0ubuntu0.20.04.3 \
    python3-dev=3.8.2-0ubuntu2 \
    sudo=1.8.31-1ubuntu1.2 \
    tk-dev=8.6.9+1 \
    uuid-dev=2.34-0.1ubuntu9.3 \
    wget=1.20.3-1ubuntu2 \
    zlib1g-dev=1:1.2.11.dfsg-2ubuntu1.3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /home/lib/python3 \
    && cd /home/lib/python3 \
    && wget https://www.python.org/ftp/python/3.10.4/Python-3.10.4.tgz \
    && tar xvf Python-3.10.4.tgz \
    && cd Python-3.10.4 \
    && ./configure \
    && make \
    && make install \
    && python3 -m pip install --upgrade pip \
    # パイプ "|" を使う場合は、エラーが発生した際にコマンド失敗にするため（正常に実行できていないのにも拘わらずビルドしてしまうことを避けるため）、"set -o pipefail"をつけること
    && set -o pipefail && curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 - --version 1.1.13

ENV LANG=ja_JP.utf8 \
    LC_ALL=ja_JP.utf8

CMD [ "bash", "/home/workspace/.devcontainer/app/create_app/create-app.sh", "your_project_name", "3.2", "13", "9.5.0" ]
# CMD [ "bash", "/home/workspace/.devcontainer/app/setup_app/setup-app.sh", "your_project_name" ]